In [1]:
import torch

## 2.1 Создание нейронов и полносвязных слоев

2.1.1. Используя операции над матрицами и векторами из библиотеки `torch`, реализовать нейрон с заданными весами `weights` и `bias`. Прогнать вектор `inputs` через нейрон и вывести результат.

In [6]:
class Neuron:
  def __init__(self, weights, bias):
    self.w = weights
    self.b=bias


  def forward(self, inputs):
    y_pred = self.w @ inputs + self.b
    return y_pred # <реализовать логику нейрона>
  #y_pred = torch.mv(inputs.view(1,-1), self.w.view(-1,1))+self.b

In [7]:
inputs = torch.tensor([1.0, 2.0, 3.0, 4.0])
weights = torch.tensor([-0.2, 0.3, -0.5, 0.7])
bias = 3.14



In [8]:
n1 = Neuron(weights, bias)
y = n1.forward(inputs)
y

tensor(4.8400)

2.1.2 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать полносвязный слой с заданными весами `weights` и `biases`. Прогнать вектор `inputs` через слой и вывести результат.

In [9]:
class Linear:
  def __init__(self, weights, biases):
    # <создать атрибуты объекта weights и biases>
    self.ws = weights
    self.bs =bias
    pass

  def forward(self, inputs):
    y_pred = torch.mm (inputs.view(1,-1),self.ws)+ self.bs
    return y_pred # <реализовать логику слоя>

In [10]:
inputs = torch.tensor([1.0, 2.0, 3.0, 4.0])
weights = torch.tensor([[-0.2, 0.3, -0.5, 0.7],
                        [0.5, -0.91, 0.26, -0.5],
                        [-0.26, -0.27, 0.17, 0.87]]).T

biases = torch.tensor([3.14, 2.71, 7.2])

In [11]:
l1 = Linear(weights, biases)
y = l1.forward(inputs)
y

tensor([[4.8400, 0.6000, 6.3300]])

2.1.3 Реализовать полносвязный слой из __2.1.2__ таким образом, чтобы он мог принимать на вход матрицу (батч) с данными. Продемонстрировать работу.
Результатом прогона сквозь слой должна быть матрица размера `batch_size` x `n_neurons`.


In [ ]:
class Linear:
  def __init__(self, batch_size,weights, biases):
    # <создать атрибуты объекта weights и biases>
    self.ws = weights
    self.bs =bias
    self.batch = batch_size
    pass

  def forward(self, inputs):
    y_pred = torch.mm (inputs.view(batch_size,-1),self.ws)+ self.bs
    return y_pred # <реализовать логику слоя>

In [ ]:
inputs = torch.tensor([[1, 2, 3, 2.5],
                       [2, 5, -1, 2],
                       [-1.5, 2.7, 3.3, -0.8]])
batch_size= inputs.size()[0]

In [ ]:
l1 = Linear(batch_size,weights,biases)
y = l1.forward(inputs)
y

tensor([[ 3.7900,  1.3500,  5.0250],
        [ 6.1400, -1.6700,  2.8400],
        [ 2.0400,  1.1910,  2.6660]])

2.1.4 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать полносвязный слой из `n_neurons` нейронов с `n_features` весами у каждого нейрона (инициализируются из стандартного нормального распределения). Прогнать вектор `inputs` через слой и вывести результат. Результатом прогона сквозь слой должна быть матрица размера `batch_size` x `n_neurons`.

In [6]:
class Linear:
  def __init__(self, n_features, n_neurons):
    # <создать атрибуты объекта weights и biases>
    self.ws = torch.randn(n_features,n_neurons)
    self.bs =torch.randn(n_neurons)
    print(self.ws)
    print(self.bs)


  def forward(self, inputs):
    return torch.matmul(inputs, self.weights) + self.biases# <реализовать логику слоя>

n_features = 4
n_neurons = 3
batch_size = 2

linear_layer = Linear(n_features, n_neurons)

tensor([[ 0.8398,  0.6193,  1.2870],
        [ 1.2931,  2.1635, -0.4976],
        [-0.4707,  1.2225,  0.3305],
        [-1.0365,  0.9047, -0.5361]])
tensor([-1.2293, -1.7727,  0.2837])


tensor([[-1.0286, -0.1512, -2.0541],
        [-0.3385, -0.2796,  0.7984],
        [-0.7742, -1.7689,  0.9328],
        [-0.2104, -1.1546, -0.5398]])
tensor([1.1965, 1.4649, 1.3903])


2.1.5 Используя решение из __2.1.4__, создать 2 полносвязных слоя и пропустить матрицу `inputs` последовательно через эти два слоя. Количество нейронов в первом слое выбрать произвольно, количество нейронов во втором слое выбрать так, чтобы результатом прогона являлась матрица (3x7).

In [ ]:
inputs = torch.tensor([[1, 2, 3, 2.5],
                       [2, 5, -1, 2],
                       [-1.5, 2.7, 3.3, -0.8]])

## 2.2 Создание функций активации

2.2.1 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию активации ReLU:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/f4353f4e3e484130504049599d2e7b040793e1eb)

Создать матрицу размера (4,3), заполненную числами из стандартного нормального распределения, и проверить работоспособность функции активации.

In [7]:
class ReLU:
    def forward(self, inputs):
        # Применяем функцию активации ReLU к входным данным
        return torch.max(torch.zeros_like(inputs), inputs)

relu = ReLU()

inputs = torch.randn(4, 3)  # Пример матрицы размера (4, 3) с данными из стандартного нормального распределения
output = relu.forward(inputs)

print("Исходные данные:")
print(inputs)
print("Результат ReLU:")
print(output)

Исходные данные:
tensor([[-1.1364, -0.5351,  1.3897],
        [ 0.3717,  1.6984,  0.4100],
        [ 0.2511,  0.2431, -1.1149],
        [-1.2264, -0.1825,  0.4658]])
Результат ReLU:
tensor([[0.0000, 0.0000, 1.3897],
        [0.3717, 1.6984, 0.4100],
        [0.2511, 0.2431, 0.0000],
        [0.0000, 0.0000, 0.4658]])


2.2.2 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию активации softmax:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/6d7500d980c313da83e4117da701bf7c8f1982f5)

Создать матрицу размера (4,3), заполненную числами из стандартного нормального распределения, и проверить работоспособность функции активации. Строки матрицы трактовать как выходы линейного слоя некоторого классификатора для 4 различных примеров.

In [8]:
class Softmax:
    def forward(self, inputs):
        exp_inputs = torch.exp(inputs - torch.max(inputs, dim=1, keepdim=True).values)
        softmax_output = exp_inputs / exp_inputs.sum(dim=1, keepdim=True)
        return softmax_output
softmax = Softmax()

inputs = torch.randn(4, 3)
output = softmax.forward(inputs)

print("Исходные данные:")
print(inputs)
print("Результат Softmax:")
print(output)


Исходные данные:
tensor([[-1.2650,  1.4443, -1.6843],
        [ 0.0258,  0.3896,  0.2775],
        [ 1.1011, -1.8096, -1.1325],
        [-0.3373,  0.4029,  1.3477]])
Результат Softmax:
tensor([[0.0600, 0.9006, 0.0394],
        [0.2685, 0.3863, 0.3453],
        [0.8609, 0.0469, 0.0922],
        [0.1178, 0.2470, 0.6352]])


2.2.3 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию активации ELU:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/eb23becd37c3602c4838e53f532163279192e4fd)

Создать матрицу размера (4,3), заполненную числами из стандартного нормального распределения, и проверить работоспособность функции активации.

In [2]:

class ELU:
  def __init__(self, alpha):
     self.alpha = alpha

  def forward(self, inputs):
    return torch.where(inputs > 0, inputs, self.alpha * (torch.exp(inputs) - 1))

elu_activation = ELU(alpha=1.0)

inputs = torch.randn(4, 3)
output = elu_activation.forward(inputs)

print("Исходные данные:")
print(inputs)
print("Результат ELU:")
print(output)

Исходные данные:
tensor([[-0.7719,  0.1027, -0.3688],
        [ 0.2679, -0.3910, -0.2987],
        [-0.1298,  1.3086,  0.2821],
        [-1.8904,  0.2318, -0.8955]])
Результат ELU:
tensor([[-0.5379,  0.1027, -0.3084],
        [ 0.2679, -0.3236, -0.2582],
        [-0.1217,  1.3086,  0.2821],
        [-0.8490,  0.2318, -0.5916]])


## 2.3 Создание функции потерь

2.3.1 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию потерь MSE:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/e258221518869aa1c6561bb75b99476c4734108e)

Создать полносвязный слой с 1 нейроном, прогнать через него батч `inputs` и посчитать значение MSE, трактуя вектор `y` как вектор правильных ответов.

In [4]:
class MSELoss:
  def forward(self, y_pred, y_true):
    mse = ((y_pred - y_true)**2).mean()
    return mse
loss = MSELoss()
linear_layer = torch.nn.Linear(4, 1)


In [5]:
inputs = torch.tensor([[1, 2, 3, 2.5],
                       [2, 5, -1, 2],
                       [-1.5, 2.7, 3.3, -0.8]])

y_true = torch.tensor([[2], [3], [4]])
y_pred = linear_layer(inputs)
mse_loss = loss.forward(y_pred, y_true)

In [7]:
print("MSE Loss:", mse_loss.item())

MSE Loss: 33.128692626953125


2.3.2 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию потерь Categorical Cross-Entropy:

<img src="https://i.ibb.co/93gy1dN/Screenshot-9.png" width="200">

Создать полносвязный слой с 3 нейронами и прогнать через него батч `inputs`. Полученный результат пропустить через функцию активации softmax. Посчитать значение CCE, трактуя вектор `y` как вектор правильных ответов.

In [19]:
class CategoricalCrossentropyLoss:
  def forward(self, y_pred, y_true):
     softmax_pred = torch.softmax(y_pred, dim=1)
     cce = -torch.log(softmax_pred.gather(1, y_true.view(-1, 1)))
     return cce.mean()

loss = CategoricalCrossentropyLoss()
linear_layer = torch.nn.Linear(4, 3)


In [20]:
inputs = torch.tensor([[1, 2, 3, 2.5],
                        [2, 5, -1, 2],
                        [-1.5, 2.7, 3.3, -0.8]])
y_true = torch.tensor([1, 0, 0])
y_pred = linear_layer(inputs)
cce_loss = loss.forward(y_pred, y_true)
print("Cross-Entropy Loss:", cce_loss.item())

Cross-Entropy Loss: 1.9353302717208862


2.3.3 Модифицировать 2.3.1, добавив L2-регуляризацию.

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/d92ca2429275bfdc0474523babbafe014ca8b580)


In [ ]:
class MSELossL2:
  def __init__(self, lambda_):
    # создать атрибут объекта alpha норма для функции потерь
    pass

  def data_loss(self, y_pred, y_true):
    # <подсчет первого слагаемого из формулы>
    pass

  def reg_loss(self, layer):
    # используйте атрибуты объекта layer, в которых хранятся веса слоя
    # <подсчет второго слагаемого из формулы>
    pass

  def forward(self, y_pred, y_true):
    return self.data_loss(y_pred, y_true) + self.reg_loss(y_pred, y_true)

## 2.4 Обратное распространение ошибки

2.4.1 Используя один нейрон и SGD (1 пример за шаг), решите задачу регрессии

In [13]:
from sklearn.datasets import make_regression

X, y, coef = make_regression(n_features=4, n_informative=4, coef=True, bias=0.5)
X = torch.from_numpy(X).to(dtype=torch.float32)
y = torch.from_numpy(y).to(dtype=torch.float32)

[Граф вычислений для этой задачи](https://i.ibb.co/2dhDxZx/photo-2021-02-15-17-18-04.jpg)

2.4.1.1 Реализуйте класс `SquaredLoss`


In [17]:
class SquaredLoss:
    def forward(self, y_pred, y_true):
        # <реализовать логику MSE>
        return (y_pred - y_true) ** 2

    def backward(self, y_pred, y_true):
        self.dinput = 2 * (y_pred - y_true)# df/dc

2.4.1.2. Модифицируйте класс `Neuron` из __2.1.1__:

  1) Сделайте так, чтобы веса нейрона инициализировались из стандартного нормального распределения

  2) Реализуйте расчет градиента относительно весов `weights` и `bias`

In [1]:
import torch
import numpy as np
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split

In [15]:
class Neuron:
    def __init__(self, n_inputs):
        # <создать атрибуты объекта weights и bias>
        self.weights = torch.randn(n_inputs)
        self.bias = torch.randn(1)

    def forward(self, inputs):
        # <реализовать логику нейрона>
        self.inputs = inputs
        return (inputs * self.weights).sum() + self.bias

    def backward(self, dvalue):
        # dvalue - значение производной, которое приходит нейрону от следующего слоя сети
        # в данном случае это будет значение df/dc (созданное методом backwards у объекта MSELoss)
        self.dweights = dvalue * self.inputs# df/dW
        self.dinput =  dvalue * self.weights# df/wX
        self.dbias = dvalue# df/db


2.4.1.3 Допишите цикл для настройки весов нейрона

[SGD](https://ru.wikipedia.org/wiki/%D0%A1%D1%82%D0%BE%D1%85%D0%B0%D1%81%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9_%D0%B3%D1%80%D0%B0%D0%B4%D0%B8%D0%B5%D0%BD%D1%82%D0%BD%D1%8B%D0%B9_%D1%81%D0%BF%D1%83%D1%81%D0%BA)

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/dda3670f8a8996a0d3bf80856bb4a166cc8db6d4)

In [18]:
n_inputs = X.shape[-1]
learning_rate = 0.1 #  скорость обучения
n_epoch = 100 #  количество эпох

neuron = Neuron(n_inputs)
loss = SquaredLoss()

losses = []
for epoch in range(100):
    for x_example, y_example in zip(X, y):
        # forward pass
        y_pred = neuron.forward(x_example)# <прогон через нейрон>
        curr_loss = loss.forward(y_pred, y_example) # <прогон через функцию потерь>
        losses.append(curr_loss)

        # backprop
        # <вызов методов backward>
        # обратите внимание на последовательность вызовов: от конца к началу
        loss.backward(y_pred, y_example)
        neuron.backward(loss.dinput)
        # <шаг оптимизации для весов (weights и bias) нейрона>
        neuron.weights -= learning_rate * neuron.dweights
        neuron.bias -= learning_rate * neuron.dbias

In [19]:
losses[::1500]


[tensor([12741.6787]),
 tensor([2.3283e-10]),
 tensor([0.]),
 tensor([0.]),
 tensor([2.3283e-10]),
 tensor([0.]),
 tensor([0.])]

2.4.2 Решите задачу 2.4.1, используя пакетный градиентный спуск

Вычисления для этой задачи:
[1](https://i.ibb.co/rmtQT6P/photo-2021-02-15-18-00-43.jpg)
[2](https://i.ibb.co/NmCFVnQ/photo-2021-02-15-18-01-17.jpg)

2.4.1.1 Модифицируйте класс `MSELoss` из __2.3.1__, реализовав расчет производной относительно предыдущего слоя с учетом того, что теперь работа ведется с батчами, а не с индивидуальными примерами


In [ ]:
class MSELoss:
  def forward(self, y_pred, y_true):
    return # <реализовать логику MSE>

  def backward(self, y_pred, y_true):
    self.dinput = # df/dy^


2.4.2.2. Модифицируйте класс `Neuron` из __2.4.1.2__:

  1) Реализуйте метод `forward` таким образом, чтобы он мог принимать на вход матрицу (батч) с данными.

  2) Реализуйте расчет градиента относительно весов `weights` и `bias` с учетом того, что теперь работа ведется с батчами, а не с индивидуальными примерами

In [ ]:
class Neuron:
  def __init__(self, n_inputs):
    # <создать атрибуты объекта weights и bias>
    pass

  def forward(self, inputs):
    return # <реализовать логику нейрона>

  def backward(self, dvalue):
    # dvalue - значение градиента, которое приходит нейрону от следующего слоя сети
    # в данном случае это будет градиент L по y^ (созданный методом backwards у объекта MSELoss)
    self.dweights = # df/dW
    self.dbias = # df/db


2.4.2.3 Допишите цикл для настройки весов нейрона

In [ ]:
n_inputs = # <размерность элемента выборки >
learning_rate = 0.1 #  скорость обучения
n_epoch = 100 #  количество эпох

neuron = Neuron(n_inputs)
loss = MSELoss()


for epoch in range(100):
    # forward pass
    y_pred = # <прогон через нейрон>
    curr_loss = # <прогон через функцию потерь>
    losses.append(curr_loss)

    # backprop
    # <вызов методов backward>
    # обратите внимание на последовательность вызовов: от конца к началу

    # <шаг оптимизации для весов (weights и bias) нейрона>

2.4.3  Используя один полносвязный слой и  пакетный градиетный спуск, решите задачу регрессии из __2.4.1__

2.4.3.1 Модифицируйте класс `Linear` из __2.1.4__. ([вычисление градиентов](https://i.ibb.co/kgVR6m6/photo-2021-02-15-21-30-28.jpg))

In [ ]:
class Linear:
  def __init__(self, n_features, n_neurons):
    # <создать атрибуты объекта weights и biases>
    pass

  def forward(self, inputs):
    return # <реализовать логику слоя>

  def backward(self, dvalues):
    self.dweights = # df/dW
    self.dbiases = # df/db
    self.dinputs = # df/dX

2.4.3.2 Создайте слой с одним нейроном. Используя класс MSELoss из 2.4.2, убедитесь, что модель обучается

2.4.4 Используя наработки из 2.4, создайте нейросеть и решите задачу регрессии.

Предлагаемая архитектура:
1. Полносвязный слой с 10 нейронами
2. Активация ReLU
3. Полносвязный слой с 1 нейроном

In [ ]:
X = torch.linspace(-1, 1, 100).view(-1, 1)
y = X.pow(2) + 0.2 * torch.rand(X.size())

In [ ]:
class Activation_ReLU:
  def forward(self, inputs):
    self.inputs = inputs
    self.output = inputs.clip(min=0)
    return self.output

  def backward(self, dvalues):
    self.dinputs = dvalues.clone()
    self.dinputs[self.inputs <= 0] = 0

In [ ]:
# создание компонентов сети
# fc1 =
# relu1 =
# fc2 =

loss = MSELoss()
lr = 0.02

ys = []
for epoch in range(2001):
  # <forward pass>
  # fc1 > relu1 > fc2 > loss

  data_loss = # <прогон через функцию потерь>

  if epoch % 200 == 0:
    print(f'epoch {epoch} mean loss {data_loss}')
    ys.append(out)

  # <backprop>
  # loss > fc2 > relu1 > fc1

  # <шаг оптимизации для fc1>

  # <шаг оптимизации для fc2>


In [ ]:
import matplotlib.pyplot as plt

fig, axs = plt.subplots(len(ys), 1, figsize=(10, 40))
for ax, y_ in zip(axs, ys):
  ax.scatter(X.numpy(), y.numpy(), color = "orange")
  ax.plot(X.numpy(), y_.numpy(), 'g-', lw=3)
  ax.set_xlim(-1.05, 1.5)
  ax.set_ylim(-0.25, 1.25)